spring:
  messages:
    encoding: UTF-8
    basename: i18n/bundle

application:
  file-resource-template: /questions-answers_%s.csv
  locale-default: ru_RU
  languages:
    ru_RU: Русский
    en: English